CREATE DATABASE modulo2_unidad1_disenosql;

USE modulo2_unidad1_disenosql;

CREATE TABLE Clientes (
id_cliente INT PRIMARY KEY ,
-- SE USA INT PORQUE LA CLAVE PRIMARIA DEBE SER UN NUMERO ENTERO
nombre VARCHAR(100) NOT NULL, 
--SE USA VARCHAR PORQUE EL NOMBRE ES UN TEXTO DE LONGITUD VARIABLE Y SE ACLARA EL NUMERO DE CARACTERES
perfil_bio TEXT NOT NULL, 
--SE USA TEXT PORQUE SE NECESITA QUE EL TEXTO SEA UNA DESCRIPCION LARGA
fecha_registro DATE NOT NULL )
--SE USA DATE PORQUE SOLO NECESITAMOS LA FECHA DEL REGISTRO, Y NO LA HORA
;

CREATE TABLE Productos (
id_producto INT PRIMARY KEY, 
--SE USA INT PORQUE LA CLAVE PRIMARIA DEBE SER UN NUMERO ENTERO
descripcion VARCHAR(255) NOT NULL,
--SE USA VARCHAR PORQUE EL NOMBRE ES UN TEXTO DE LONGITUD VARIABLE Y SE ACLARA EL NUMERO DE CARACTERES
precio DECIMAL(10,2) NOT NULL, 
--SE USA DECIMAL PORQUE EL PRECIO PUEDE SER UN NUMERO NO ENTERO Y SE ACLARA LA LONGITUD DEL NUMERO ENTERO Y LA CANTIDAD DE DECIMALES
esta_activo INT NOT NULL )
--SE USA INT PORQUE PODEMOS ELEGIR EL NUMERO 1 PARA DECIR QUE ESTA ACTIVO Y EL NUMERO 2 PARA DECIR QUE NO ESTA ACTIVO Y NO SE ENCUENTRA A LA VENTA
;